In [ ]:
import numpy as np
import cv2

In [ ]:
img = np.array([[0,0,0,0,1,1,1,0,0,0,0],
 [0,0,0,1,1,2,1,1,0,0,0],
  [1,1,4,5,7,13,7,5,4,1,1],
   [1,1,7,6,8,14,8,6,7,1,1],
    [2,2,7,5,11,15,11,5,7,2,2],
    [2,5,11,9,12,15,12,9,11,5,2],
    [2,2,7,5,11,15,11,5,7,2,2],
     [1,1,7,6,8,14,8,6,7,1,1],
      [1,1,4,5,7,13,7,5,4,1,1],
      [0,0,0,1,1,2,1,1,0,0,0],
      [0,0,0,0,1,1,1,0,0,0,0]]
               )

In [ ]:
smoothed_img = np.empty((11, 11))

In [ ]:
for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    if (i == 0 and j == 0):
      smoothed_img[i,j] = img[i,j] = 4 * img[i,j] + 2 * img[i,j+1] + 2 * img[i+1,j] + 1 * img[i+1,j+1]
    elif(i== 0 and j == 10) :
      smoothed_img[i,j] = 2 * img[i,j-1] + 4 * img[i,j] + 1 * img[i+1,j-1] + 2 * img[i+1,j]
    elif(i == 10 and j == 0 ):
      smoothed_img[i,j] = 4 * img[i,j] + 2 * img[i,j+1] + 2 * img[i-1,j] + 1 * img[i-1,j+1]
    elif(i == 10 and j == 10):
      smoothed_img[i,j] = 4 * img[i,j] + 2 * img[i,j-1] + 2 * img[i-1 , j] + 1 * img[i-1,j-1]
    elif( i == 0 and j != 10 and j!= 0):
      smoothed_img[i,j] =  2 * img[i,j-1] + 4 * img[i,j] + 2*img[i,j+1] + 1 *img[i+1,j-1] + 2 * img[i+1,j] + 1 * img[i+1,j+1]
    elif( i == 10 and j != 0 and j!=10):
      smoothed_img[i,j] = 1 * img[i-1,j-1] + 2 * img[i-1,j] + 1 * img[i-1,j+1]
      + 2 * img[i,j-1] + 4 * img[i,j] + 2*img[i,j+1]
    elif ( j == 0 and i != 0 and i!= 10) :
      smoothed_img[i,j] =  2 * img[i-1,j] + 1 * img[i-1,j+1]
      + 4 * img[i,j] + 2*img[i,j+1] + 2 * img[i+1,j] + 1 * img[i+1,j+1]
    elif(j == 10 and i != 0 and i!= 10) :
      smoothed_img[i,j] = 1*img[i-1,j-1] + 2 * img[i-1,j]
      + 2 * img[i,j-1] + 4 * img[i,j] + 1 *img[i+1,j-1] + 2 * img[i+1,j]
    else:
     smoothed_img[i,j] = 1*img[i-1,j-1] + 2 * img[i-1,j] + 1 * img[i-1,j+1]
     + 2 * img[i,j-1] + 4 * img[i,j] + 2*img[i,j+1] + 1 *img[i+1,j-1] + 2 * img[i+1,j] + 1 * img[i+1,j+1]

In [ ]:
print(smoothed_img)

[[ 0.  0.  1.  5. 11. 14. 11.  5.  1.  0.  0.]
 [ 0.  0.  0.  1.  3.  4.  3.  1.  0.  0.  0.]
 [ 0.  0.  1.  3.  5.  6.  5.  3.  1.  0.  0.]
 [ 3.  7. 14. 21. 32. 40. 32. 21. 14.  7.  3.]
 [ 3. 10. 21. 27. 36. 44. 36. 27. 21. 10.  3.]
 [ 6. 13. 21. 28. 42. 52. 42. 28. 21. 13.  6.]
 [ 9. 23. 36. 41. 48. 54. 48. 41. 36. 23.  9.]
 [ 6. 13. 21. 28. 42. 52. 42. 28. 21. 13.  6.]
 [ 3. 10. 21. 27. 36. 44. 36. 27. 21. 10.  3.]
 [ 3.  7. 14. 21. 32. 40. 32. 21. 14.  7.  3.]
 [ 0.  0.  1.  3.  5.  6.  5.  3.  1.  0.  0.]]


In [ ]:
kernel_x = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
kernel_y = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

In [ ]:
gradient_mag = np.empty((11, 11))

In [ ]:
gradient_angle = np.empty((11, 11))

In [ ]:
for x in range(1, smoothed_img.shape[0] - 1):
    for y in range(1, smoothed_img.shape[1] - 1):
        window = smoothed_img[x - 1 : x + 2, y - 1 : y + 2]
        mag_x = np.sum(window * kernel_x)
        mag_y = np.sum(window * kernel_y)
        gradient_angle[x,y] = np.arctan2(mag_y, mag_x)
        gradient_mag[x, y] = np.sqrt(mag_x**2 + mag_y**2)

In [ ]:
print(gradient_mag)

[[  0.           0.           1.           5.          11.
   14.          11.           5.           1.           0.
    0.        ]
 [  0.           2.          10.19803903  22.36067977  28.42534081
   28.          28.42534081  22.36067977  10.19803903   2.
    0.        ]
 [  0.          33.61547263  58.87274412  87.92041856 117.38824473
  130.         117.38824473  87.92041856  58.87274412  33.61547263
    0.        ]
 [  3.          59.41380311  88.20430828 113.25193155 136.89411967
  138.         136.89411967 113.25193155  88.20430828  59.41380311
    3.        ]
 [  3.          65.78753681  68.54195795  75.6439026   86.31338251
   44.          86.31338251  75.6439026   68.54195795  65.78753681
    3.        ]
 [  6.          88.50988645  86.45229899  88.23831367  91.58602513
   44.          91.58602513  88.23831367  86.45229899  88.50988645
    6.        ]
 [  9.          84.          66.          66.          74.
    0.          74.          66.          66.          84.
    9.

In [ ]:
gradient_mag = np.round(gradient_mag, 0)


In [ ]:
print(gradient_mag)

[[  0.   0.   1.   5.  11.  14.  11.   5.   1.   0.   0.]
 [  0.   2.  10.  22.  28.  28.  28.  22.  10.   2.   0.]
 [  0.  34.  59.  88. 117. 130. 117.  88.  59.  34.   0.]
 [  3.  59.  88. 113. 137. 138. 137. 113.  88.  59.   3.]
 [  3.  66.  69.  76.  86.  44.  86.  76.  69.  66.   3.]
 [  6.  89.  86.  88.  92.  44.  92.  88.  86.  89.   6.]
 [  9.  84.  66.  66.  74.   0.  74.  66.  66.  84.   9.]
 [  6.  89.  86.  88.  92.  44.  92.  88.  86.  89.   6.]
 [  3.  66.  69.  76.  86.  44.  86.  76.  69.  66.   3.]
 [  3.  59.  88. 113. 137. 138. 137. 113.  88.  59.   3.]
 [  0.   0.   1.   3.   5.   6.   5.   3.   1.   0.   0.]]


In [ ]:
nms_image = np.zeros_like(img)

In [ ]:
gradient_angle

array([[ 6.86724078e-310,  6.86724078e-310,  4.86495785e-310,
         4.86495785e-310,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000, -1.97395560e-001,
        -4.63647609e-001, -8.85066816e-001, -1.57079633e+000,
        -2.25652584e+000, -2.67794504e+000, -2.94419709e+000,
         3.14159265e+000,  0.00000000e+000],
       [ 0.00000000e+000,  1.17371688e+000,  1.20606151e+000,
         1.23465828e+000,  1.32994987e+000,  1.57079633e+000,
         1.81164278e+000,  1.90693438e+000,  1.93553114e+000,
         1.96787577e+000,  0.00000000e+000],
       [ 0.00000000e+000,  8.09203190e-001,  9.95371676e-001,
         1.06369782e+000,  1.13328655e+000,  1.57079633e+000,
         2.00830610e+000,  2.07789483e+000,  2.14622098e+000,
         2.33238946e+000,  0.00000000e+000],
       [ 0.00000000e+000,  3.40978953e-001,  4.04891786e-001,
         4.222

In [ ]:
for x in range(1, img.shape[0] - 1):
    for y in range(1, img.shape[1] - 1):
        angle = gradient_angle[x, y]
        mag1, mag2 = gradient_mag[x - 1, y], gradient_mag[x + 1, y]
        if (angle >= 0 and mag1 <= gradient_mag[x, y] >= mag2) or \
           (angle < 0 and mag1 <= gradient_mag[x, y] >= mag2):
            nms_image[x, y] = gradient_mag[x, y]

In [ ]:
print(nms_image)

[[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  88 113 137 138 137 113  88   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0  89  86  88  92  44  92  88  86  89   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0  89  86  88  92  44  92  88  86  89   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  88 113 137 138 137 113  88   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]]


In [ ]:
low_threshold = 88
high_threshold = 100

In [ ]:
edge_map = np.zeros_like(img)

In [ ]:
edge_map[(nms_image >= low_threshold) & (nms_image < high_threshold)] = 128 #weak edges
edge_map[(nms_image >= high_threshold)] = 255 #strong edges

In [ ]:
edge_map

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 128, 255, 255, 255, 255, 255, 128,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 128,   0, 128, 128,   0, 128, 128,   0, 128,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 128,   0, 128, 128,   0, 128, 128,   0, 128,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 128, 255, 255, 255, 255, 255, 128,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [ ]:
#weak edges that are connected to the strong edges are considered edge but the others are considered as "not an edge"

In [ ]:
for i in range(edge_map.shape[0] -1):
  for j in range(edge_map.shape[1] - 1) :
    if(i!= 0 and j != 0):
      if(edge_map[i-1,j] == 255 or edge_map[i,j-1] == 255 or edge_map[i,j+1] == 255 or edge_map[i+1,j] == 255 ) :
        continue
      else:
        edge_map[i,j] = 0

In [ ]:
print(edge_map)

[[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 128 255 255 255 255 255 128   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 128 255 255 255 255 255 128   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]]
